// PV Tool — Copyright (c) 2026 DanteAlighieri13210914
// Licensed under Non-Commercial License. See LICENSE for terms.
// Generated by scripts/extract-effect-parameters.mjs; supplement dynamic defaults in effectParameters.ts.
export const effectParameterInventory: Record<string, Record<string, { type: string; default?: any; options?: any[]; min?: number; max?: number; step?: number }>> = {
  "backgroundBlocks": {
    "count": {"type":"number","default":7,"min":0,"step":1},
    "alpha": {"type":"number","default":0.5,"min":0,"max":1,"step":0.01}
  },
  "balancingCircles": {
    "count": {"type":"number","default":5,"min":0,"step":1},
    "blueColor": {"type":"string","default":"#0028B4"},
    "whiteColor": {"type":"string","default":"#ffffff"},
    "glowAlpha": {"type":"number","default":0.4,"min":0,"max":1,"step":0.01}
  },
  "bigOutlineText": {
    "color": {"type":"string","default":"#e0e0e0"},
    "strokeColor": {"type":"string","default":"#ffffff"},
    "fontFamily": {"type":"string","default":"\"Noto Sans JP\", \"Hiragino Kaku Gothic Pro\", sans-serif"},
    "fontSize": {"type":"number","default":0,"step":0.01},
    "staggerDelay": {"type":"number","default":0.15,"step":0.01},
    "spacingFrac": {"type":"number","default":1.3,"step":0.01},
    "staggerY": {"type":"unknown"}
  },
  "bloodSplatter": {
    "count": {"type":"number","default":4,"min":0,"step":1},
    "color": {"type":"string","default":"#8b0000"},
    "alpha": {"type":"number","default":0.92,"min":0,"max":1,"step":0.01},
    "size": {"type":"number","default":1,"step":0.01},
    "seed": {"type":"number","default":42,"min":0,"step":1}
  },
  "breathingBlocks": {
    "count": {"type":"number","default":8,"min":0,"step":1},
    "minSize": {"type":"number","default":0.15,"step":0.01},
    "maxSize": {"type":"number","default":0.55,"step":0.01},
    "minBrightness": {"type":"number","default":180,"step":0.01},
    "maxBrightness": {"type":"number","default":255,"step":0.01}
  },
  "burstLines": {
    "rotSpeed": {"type":"number","default":0.05,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "color": {"type":"string","default":"$secondary"},
    "alpha": {"type":"number","default":0.25,"min":0,"max":1,"step":0.01},
    "rayCount": {"type":"number","default":24,"min":0,"step":1},
    "innerRadius": {"type":"number","default":0.08,"step":0.01},
    "outerRadius": {"type":"number","default":0.7,"step":0.01},
    "lineWidth": {"type":"number","default":1,"step":0.01}
  },
  "centeredSquares": {
    "outerSize": {"type":"number","default":300,"step":0.01},
    "midSize": {"type":"number","default":220,"step":0.01},
    "innerSize": {"type":"number","default":160,"step":0.01},
    "borderColor": {"type":"string","default":"$primary"},
    "midColor": {"type":"string","default":"$primary"},
    "innerColor": {"type":"string","default":"$secondary"}
  },
  "checkerboard": {
    "cellSize": {"type":"number","default":40,"step":0.01},
    "color1": {"type":"string","default":"#000000"},
    "color2": {"type":"string","default":"#ffffff"},
    "alpha": {"type":"number","default":0.08,"min":0,"max":1,"step":0.01}
  },
  "chromaticAberration": {
    "offset": {"type":"number","default":3,"step":0.01},
    "flickerSpeed": {"type":"number","default":4,"step":0.01}
  },
  "colorMask": {
    "color": {"type":"string","default":"$accent"},
    "alpha": {"type":"number","default":0.3,"min":0,"max":1,"step":0.01},
    "coverage": {"type":"object","default":{"x":0,"y":0,"w":1,"h":1}}
  },
  "compositionGuides": {
    "rotSpeed": {"type":"number","default":0,"step":0.01},
    "color": {"type":"string","default":"$text"},
    "alpha": {"type":"number","default":0.2,"min":0,"max":1,"step":0.01},
    "lineWidth": {"type":"number","default":1,"step":0.01},
    "guides": {"type":"array","default":["goldenSpiral"]},
    "spiralQuadrant": {"type":"number","default":0,"step":0.01}
  },
  "concentricCircles": {
    "count": {"type":"number","default":4,"min":0,"step":1},
    "maxRadius": {"type":"number","default":250,"step":0.01},
    "strokeWidth": {"type":"number","default":1.5,"step":0.01},
    "color": {"type":"string","default":"$primary"},
    "alpha": {"type":"number","default":0.6,"min":0,"max":1,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "animation": {"type":"string","default":"rotate","options":["rotate","pulse"]},
    "animationSpeed": {"type":"number","default":0.15,"step":0.01}
  },
  "crayonShatter": {
    "fontSize": {"type":"number","default":130,"step":0.01},
    "fontFamily": {"type":"string","default":"\"Yu Gothic\", \"Hiragino Sans\", \"Helvetica Neue\", Arial, sans-serif"},
    "fontWeight": {"type":"string","default":"700"},
    "alphaThreshold": {"type":"number","default":60,"min":0,"max":255,"step":1},
    "minAreaFrac": {"type":"number","default":0.001,"step":0.01},
    "preErosionIters": {"type":"number","default":0,"step":0.01,"min":0},
    "charSpacingFrac": {"type":"number","default":1.05,"step":0.01},
    "colSpacingFrac": {"type":"number","default":1.4,"min":0,"step":1},
    "colors": {"type":"unknown"},
    "baseColor": {"type":"string","default":"#5a3a5a"},
    "replacements": {"type":"object","default":{}},
    "replaceProb": {"type":"number","default":0.35,"min":0,"max":1,"step":0.01},
    "offsetProb": {"type":"number","default":0.55,"min":0,"max":1,"step":0.01},
    "rotateProb": {"type":"number","default":0.55,"min":0,"max":1,"step":0.01},
    "outlineProb": {"type":"number","default":0.65,"min":0,"max":1,"step":0.01},
    "swingProb": {"type":"number","default":0,"min":0,"max":1,"step":0.01},
    "maxOffsetPx": {"type":"number","default":5,"step":0.01,"min":0},
    "maxRotateDeg": {"type":"number","default":14,"step":0.01,"min":0},
    "randomReplaceMaxSizeFrac": {"type":"number","default":0.32,"step":0.01,"min":0},
    "outlineLineWidth": {"type":"number","default":1.5,"step":0.01},
    "outlineJitter": {"type":"number","default":0.6,"step":0.01},
    "outlineSimplify": {"type":"number","default":6,"step":0.01,"min":1},
    "outlineSmoothIters": {"type":"number","default":2,"step":0.01,"min":0},
    "outlineHalo": {"type":"unknown"},
    "outlineColor": {"type":"string","default":"base","options":["base","tint"]},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "colRowPhase": {"type":"number","default":0.45,"step":0.01},
    "layoutJitter": {"type":"number","default":0.05,"step":0.01},
    "spinSpeedScale": {"type":"number","default":1,"step":0.01},
    "frameHoldSec": {"type":"number","default":0.18,"step":0.01},
    "frameCount": {"type":"number","default":4,"min":2,"step":1}
  },
  "crimeTape": {
    "count": {"type":"number","default":5,"min":0,"step":1},
    "text": {"type":"string","default":"POLICE LINE DO NOT CROSS"},
    "tapeColor": {"type":"string","default":"#f5c800"},
    "textColor": {"type":"string","default":"#000000"},
    "tapeWidth": {"type":"number","default":52,"step":0.01},
    "speed": {"type":"number","default":80,"step":0.01},
    "angleRange": {"type":"number","default":0.18,"step":0.01},
    "colorOverrides": {"type":"object","default":{"#000000":"#000000"}}
  },
  "crossPattern": {
    "spacing": {"type":"number","default":40,"step":0.01},
    "size": {"type":"number","default":4,"step":0.01},
    "color": {"type":"string","default":"$accent"},
    "alpha": {"type":"number","default":0.4,"min":0,"max":1,"step":0.01},
    "area": {"type":"object","default":{"x":0.2,"y":0.1,"w":0.6,"h":0.8}},
    "driftSpeed": {"type":"number","default":0.2,"step":0.01}
  },
  "cuteOutlineText": {
    "text": {"type":"unknown"},
    "fontSize": {"type":"number","default":80,"step":0.01},
    "fontFamily": {"type":"string","default":"\"Noto Sans JP\", \"Hiragino Kaku Gothic Pro\", sans-serif"},
    "fillColor": {"type":"string","default":"#fab2b5"},
    "strokeColor": {"type":"string","default":"#ffffff"},
    "strokeWidth": {"type":"number","default":8,"step":0.01},
    "fontWeight": {"type":"string","default":"900"},
    "letterSpacing": {"type":"number","default":4,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "animationSpeed": {"type":"number","default":0.5,"step":0.01},
    "animationAmount": {"type":"number","default":0.02,"step":0.01}
  },
  "dashedGuideLines": {
    "color": {"type":"string","default":"#cc0000"},
    "dashLength": {"type":"number","default":12,"step":0.01},
    "gapLength": {"type":"number","default":8,"step":0.01},
    "lineWidth": {"type":"number","default":2,"step":0.01},
    "alpha": {"type":"number","default":0.8,"min":0,"max":1,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "width": {"type":"number","default":0.4,"step":0.01},
    "height": {"type":"number","default":0.55,"step":0.01},
    "extend": {"type":"number","default":60,"step":0.01},
    "crossSize": {"type":"number","default":12,"step":0.01}
  },
  "dataMonitors": {
    "count": {"type":"number","default":4,"min":0,"step":1},
    "borderColor": {"type":"string","default":"#ffffff"},
    "fillColor": {"type":"string","default":"#000000"},
    "dataColor": {"type":"string","default":"#ffffff"},
    "alpha": {"type":"number","default":0.7,"min":0,"max":1,"step":0.01}
  },
  "desktopIcon": {
    "iconsData": {"type":"unknown"},
    "x": {"type":"number","default":60,"step":0.01},
    "y": {"type":"number","default":60,"step":0.01},
    "size": {"type":"number","default":64,"step":0.01},
    "iconType": {"type":"string","default":"paint","options":["paint","notes"]},
    "fontFamily": {"type":"string","default":"\"Courier New\", monospace"},
    "labelColor": {"type":"string","default":"$text"},
    "label": {"type":"string","default":"Icon"},
    "colorOverrides": {"type":"object","default":{"#b3d9ff":"#b3d9ff","#6bb3ff":"#6bb3ff","#ffb3d9":"#ffb3d9","#ff80bf":"#ff80bf","#000000":"#000000","#ffffff":"#ffffff","#ff6b6b":"#ff6b6b","#4ecdc4":"#4ecdc4","#ffe66d":"#ffe66d","#a8e6cf":"#a8e6cf","#fffacd":"#fffacd","#f0e68c":"#f0e68c","#8b7355":"#8b7355"}}
  },
  "diagonalFill": {
    "shape": {"type":"string","default":"bowtie","options":["bowtie","diamond","rect"]},
    "color": {"type":"string","default":"$accent"},
    "lineSpacing": {"type":"number","default":6,"step":0.01},
    "lineWidth": {"type":"number","default":1.5,"step":0.01},
    "alpha": {"type":"number","default":0.85,"min":0,"max":1,"step":0.01},
    "size": {"type":"number","default":300,"step":0.01},
    "lineColor": {"type":"string","default":"$background"},
    "rectWidth": {"type":"unknown"},
    "rectHeight": {"type":"unknown"},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "animationSpeed": {"type":"number","default":0.05,"step":0.01}
  },
  "diagonalHatch": {
    "spacing": {"type":"number","default":8,"step":0.01},
    "lineWidth": {"type":"number","default":0.8,"step":0.01},
    "color": {"type":"string","default":"$accent"},
    "alpha": {"type":"number","default":0.15,"min":0,"max":1,"step":0.01}
  },
  "diagonalSplit": {
    "hatchSpacing": {"type":"number","default":6,"step":0.01},
    "rotSpeed": {"type":"number","default":0.15,"step":0.01},
    "baseHalfAngle": {"type":"number","default":0.6,"step":0.01},
    "angleVariation": {"type":"number","default":0.3,"step":0.01},
    "initRotation": {"type":"unknown"},
    "color": {"type":"string","default":"$accent"},
    "alpha": {"type":"number","default":1,"min":0,"max":1,"step":0.01},
    "centerSize": {"type":"number","default":12,"step":0.01},
    "centerColor": {"type":"string","default":"$primary"}
  },
  "diagonalStructure": {
    "color": {"type":"string","default":"#f0f0f0"},
    "alpha": {"type":"number","default":0.3,"min":0,"max":1,"step":0.01},
    "step": {"type":"number","default":100,"step":0.01}
  },
  "diamondShapes": {
    "count": {"type":"number","default":3,"min":0,"step":1},
    "maxSize": {"type":"number","default":300,"step":0.01},
    "strokeWidth": {"type":"number","default":2,"step":0.01},
    "color": {"type":"string","default":"$primary"},
    "fill": {"type":"unknown"},
    "alpha": {"type":"number","default":0.7,"min":0,"max":1,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "animationSpeed": {"type":"number","default":0.08,"step":0.01}
  },
  "dotScreen": {
    "spacing": {"type":"number","default":8,"step":0.01},
    "dotRadius": {"type":"number","default":1.5,"step":0.01},
    "color": {"type":"string","default":"$text"},
    "alpha": {"type":"number","default":0.12,"min":0,"max":1,"step":0.01},
    "angle": {"type":"number","default":15,"step":0.01}
  },
  "edgeClouds": {
    "cloudCount": {"type":"number","default":5,"min":0,"step":1},
    "minCircles": {"type":"number","default":6,"step":0.01},
    "maxCircles": {"type":"number","default":10,"step":0.01},
    "seed": {"type":"number","default":42,"min":0,"step":1},
    "baseRadius": {"type":"number","default":100,"step":0.01},
    "color": {"type":"string","default":"#ffffff"},
    "alpha": {"type":"number","default":1,"min":0,"max":1,"step":0.01},
    "animate": {"type":"unknown"},
    "animSpeed": {"type":"number","default":0.3,"step":0.01},
    "shadowOffsetX": {"type":"number","default":4,"step":0.01},
    "shadowOffsetY": {"type":"number","default":4,"step":0.01},
    "shadowAlpha": {"type":"number","default":0.5,"min":0,"max":1,"step":0.01},
    "shadowColor": {"type":"string","default":"#ead9ecff"}
  },
  "fallingText": {
    "chars": {"type":"unknown"},
    "count": {"type":"number","default":30,"min":0,"step":1},
    "color": {"type":"string","default":"$accent"},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", \"Yu Mincho\", serif"},
    "minSize": {"type":"number","default":28,"step":0.01},
    "maxSize": {"type":"number","default":72,"step":0.01},
    "colorOverrides": {"type":"object","default":{"#000000":"#000000"}}
  },
  "filmGrain": {
    "alpha": {"type":"number","default":0.08,"min":0,"max":1,"step":0.01},
    "mono": {"type":"boolean","default":true},
    "updateInterval": {"type":"number","default":3,"min":0,"step":1}
  },
  "flowingLines": {
    "count": {"type":"number","default":3,"min":0,"step":1},
    "color": {"type":"string","default":"$secondary"},
    "alpha": {"type":"number","default":0.5,"min":0,"max":1,"step":0.01},
    "strokeWidth": {"type":"number","default":1.5,"step":0.01},
    "amplitude": {"type":"number","default":80,"step":0.01},
    "frequency": {"type":"number","default":0.005,"step":0.01},
    "speed": {"type":"number","default":0.5,"step":0.01}
  },
  "formulaText": {
    "color": {"type":"string","default":"$text"},
    "fontFamily": {"type":"string","default":"\"SF Mono\", \"Fira Code\", \"Consolas\", monospace"},
    "count": {"type":"number","default":18,"min":0,"step":1},
    "formulas": {"type":"array","default":["iℏ ∂/∂t Ψ = [-ℏ²/2m ∇² + V] Ψ","ρ(∂v/∂t + v·∇v) = -∇p + μ∇²v + f","∇·E = ρ/ε₀","∇·B = 0","∇×E = -∂B/∂t","∇×B = μ₀(J + ε₀ ∂E/∂t)","G_μν + Λg_μν = (8πG/c⁴) T_μν","F(k) = ∫f(x) e^(-2πikx) dx","E² = (pc)² + (mc²)²","Δx·Δp ≥ ℏ/2","∂²u/∂t² = c²∇²u","S = k_B ln Ω","dS/dt ≥ 0","H = Σ pq̇ - L","∮ E·dl = -dΦ_B/dt"]},
    "formulaRatio": {"type":"number","default":0.65,"step":0.01}
  },
  "glitchBars": {
    "spawnRate": {"type":"number","default":0.15,"step":0.01},
    "maxBars": {"type":"number","default":8,"step":0.01},
    "color": {"type":"string","default":"$primary"},
    "alpha": {"type":"number","default":0.9,"min":0,"max":1,"step":0.01},
    "minHeight": {"type":"number","default":2,"step":0.01},
    "maxHeight": {"type":"number","default":12,"step":0.01}
  },
  "glowRing": {
    "colorInner": {"type":"string","default":"#4444ff"},
    "colorOuter": {"type":"string","default":"#cc22aa"},
    "radius": {"type":"number","default":0.38,"step":0.01},
    "ringWidth": {"type":"number","default":0.12,"step":0.01},
    "alpha": {"type":"number","default":0.7,"min":0,"max":1,"step":0.01}
  },
  "glowTextCards": {
    "cardColor": {"type":"string","default":"#ffffff"},
    "textColor": {"type":"string","default":"#1a1a1a"},
    "glowAlpha": {"type":"number","default":0.6,"min":0,"max":1,"step":0.01},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", \"Yu Mincho\", serif"},
    "fontSize": {"type":"number","default":70,"step":0.01},
    "charsPerRow": {"type":"number","default":5,"step":0.01},
    "sizeVariance": {"type":"number","default":0.3,"step":0.01},
    "staggerX": {"type":"number","default":12,"step":0.01},
    "staggerY": {"type":"number","default":8,"step":0.01},
    "cardPadding": {"type":"number","default":18,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "staggerDelay": {"type":"number","default":0.06,"step":0.01},
    "text": {"type":"unknown"}
  },
  "gradientOverlay": {
    "colorTop": {"type":"string","default":"#004040"},
    "colorBottom": {"type":"string","default":"#001a2e"},
    "alpha": {"type":"number","default":0.55,"min":0,"max":1,"step":0.01},
    "mode": {"type":"string","default":"linear","options":["linear","radial"]},
    "colorMid": {"type":"unknown"}
  },
  "halftoneBlocks": {
    "count": {"type":"number","default":8,"min":0,"step":1},
    "color": {"type":"string","default":"$primary"},
    "blockSize": {"type":"number","default":60,"step":0.01},
    "dotSpacing": {"type":"number","default":6,"step":0.01},
    "dotRadius": {"type":"number","default":1.5,"step":0.01},
    "alpha": {"type":"number","default":0.5,"min":0,"max":1,"step":0.01}
  },
  "heroText": {
    "text": {"type":"unknown"},
    "fontSize": {"type":"number","default":120,"step":0.01},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", \"Yu Mincho\", \"MS Mincho\", serif"},
    "color": {"type":"string","default":"$text"},
    "fontWeight": {"type":"string","default":"bold"},
    "letterSpacing": {"type":"number","default":8,"step":0.01},
    "rotation": {"type":"number","default":0,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "animation": {"type":"string","default":"breathe","options":["breathe","rotate"]},
    "animationSpeed": {"type":"number","default":0.5,"step":0.01},
    "animationAmount": {"type":"number","default":0.03,"step":0.01},
    "rotationSpeed": {"type":"number","default":0.1,"step":0.01}
  },
  "hudCorners": {
    "color": {"type":"string","default":"$primary"},
    "alpha": {"type":"number","default":0.9,"min":0,"max":1,"step":0.01},
    "margin": {"type":"number","default":20,"step":0.01},
    "armLength": {"type":"number","default":40,"step":0.01},
    "lineWidth": {"type":"number","default":2,"step":0.01}
  },
  "hudInfoPanel": {
    "panelWidth": {"type":"number","default":240,"step":0.01},
    "panelHeight": {"type":"number","default":420,"step":0.01},
    "primaryColor": {"type":"string","default":"$primary"},
    "alertColor": {"type":"string","default":"$accent"},
    "textColor": {"type":"string","default":"$text"},
    "gridColor": {"type":"string","default":"#323200"},
    "fontFamily": {"type":"string","default":"\"Courier New\", monospace"},
    "colorOverrides": {"type":"object","default":{"#000000":"#000000"}}
  },
  "hudStatusText": {
    "textColor": {"type":"string","default":"$text"},
    "alertColor": {"type":"string","default":"$accent"},
    "fontFamily": {"type":"string","default":"\"Courier New\", monospace"},
    "centerText": {"type":"string","default":"SYS.MONITOR // ONLINE"},
    "rightText": {"type":"string","default":"NETWATCH // PROTOCOL V.2.0.77"},
    "fontSize": {"type":"number","default":13,"step":0.01}
  },
  "jigsawGrid": {
    "seed": {"type":"number","default":914,"min":0,"step":1},
    "cols": {"type":"number","default":8,"min":0,"step":1},
    "rows": {"type":"number","default":5,"min":0,"step":1},
    "color": {"type":"string","default":"$line"},
    "alpha": {"type":"number","default":0.5,"min":0,"max":1,"step":0.01},
    "lineWidth": {"type":"number","default":2,"step":0.01},
    "tabScale": {"type":"number","default":0.2,"step":0.01}
  },
  "layeredText": {
    "maxLayers": {"type":"number","default":4,"step":0.01},
    "color": {"type":"string","default":"$primary"},
    "fontSize": {"type":"number","default":80,"step":0.01},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", serif"}
  },
  "lightSpot": {
    "color": {"type":"string","default":"#ffffff"},
    "alpha": {"type":"number","default":0.45,"min":0,"max":1,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.1,"step":0.01},
    "size": {"type":"number","default":0.5,"step":0.01}
  },
  "motionBrackets": {
    "color": {"type":"string","default":"#00ffcc"},
    "alpha": {"type":"number","default":0.8,"min":0,"max":1,"step":0.01},
    "lineWidth": {"type":"number","default":2,"step":0.01},
    "style": {"type":"string","default":"high","options":["high","medium"]},
    "showConnections": {"type":"boolean","default":false},
    "showTrails": {"type":"boolean","default":false},
    "showNodes": {"type":"boolean","default":false},
    "connColor": {"type":"unknown"},
    "trailColor": {"type":"unknown"},
    "nodeColor": {"type":"unknown"},
    "connMaxDist": {"type":"number","default":350,"step":0.01},
    "colorOverrides": {"type":"object","default":{"#00ffcc":"#00ffcc","#000000":"#000000"}}
  },
  "noiseText": {
    "count": {"type":"number","default":12,"min":0,"step":1},
    "color": {"type":"string","default":"#ffffff"},
    "bgColor": {"type":"string","default":"#000000"}
  },
  "organicBlob": {
    "shape": {"type":"string","default":"blob","options":["blob","wave","cloud"]},
    "color": {"type":"string","default":"$primary"},
    "alpha": {"type":"number","default":0.25,"min":0,"max":1,"step":0.01},
    "filled": {"type":"boolean","default":true},
    "lineWidth": {"type":"number","default":2,"step":0.01},
    "count": {"type":"number","default":3,"min":0,"step":1},
    "points": {"type":"number","default":80,"min":0,"step":1},
    "noiseScale": {"type":"number","default":3,"step":0.01},
    "noiseAmp": {"type":"number","default":0.35,"step":0.01},
    "scale": {"type":"number","default":1,"step":0.01},
    "layers": {"type":"number","default":4,"step":0.01},
    "waveY": {"type":"number","default":0.6,"step":0.01},
    "amplitude": {"type":"number","default":40,"step":0.01},
    "foamColor": {"type":"string","default":"#ffffff"}
  },
  "paperTear": {
    "seed": {"type":"number","default":42,"min":0,"step":1},
    "fillColor": {"type":"unknown"},
    "edgeColor": {"type":"string","default":"#000000"},
    "borderWidth": {"type":"number","default":7,"step":0.01},
    "animate": {"type":"unknown"}
  },
  "parallelogramStripes": {
    "skewAngle": {"type":"number","default":20,"step":0.01},
    "alpha": {"type":"number","default":0.92,"min":0,"max":1,"step":0.01},
    "paras": {"type":"array","default":[{"xFrac":-0.15,"widthFrac":0.38,"color1":"$background","color2":"$primary","texture":"none","phase":0},{"xFrac":0.1,"widthFrac":0.32,"color1":"$primary","color2":"$secondary","texture":"none","phase":1.2},{"xFrac":0.3,"widthFrac":0.3,"color1":"$accent","color2":"$accent","texture":"halftone","phase":2.4},{"xFrac":0.48,"widthFrac":0.26,"color1":"$secondary","color2":"$secondary","texture":"checkerboard","phase":3.6},{"xFrac":0.62,"widthFrac":0.32,"color1":"$secondary","color2":"$primary","texture":"none","phase":4.8},{"xFrac":0.82,"widthFrac":0.3,"color1":"$primary","color2":"$background","texture":"none","phase":0.6}]},
    "dotSpacing": {"type":"number","default":10,"step":0.01},
    "dotRadius": {"type":"number","default":3,"step":0.01},
    "cellSize": {"type":"number","default":8,"step":0.01},
    "moveSpeed": {"type":"number","default":0.3,"step":0.01}
  },
  "perspectiveGrid": {
    "mode": {"type":"string","default":"floor","options":["floor","full"]},
    "color": {"type":"string","default":"$primary"},
    "alpha": {"type":"number","default":0.3,"min":0,"max":1,"step":0.01},
    "lineWidth": {"type":"number","default":1,"step":0.01},
    "scrollSpeed": {"type":"number","default":0.5,"step":0.01},
    "vpX": {"type":"number","default":0.5,"step":0.01},
    "vpY": {"type":"unknown"},
    "vLines": {"type":"number","default":20,"step":0.01},
    "hLines": {"type":"number","default":15,"step":0.01},
    "rayCount": {"type":"number","default":24,"min":0,"step":1},
    "rings": {"type":"number","default":6,"step":0.01}
  },
  "pinkGrid": {
    "cellSize": {"type":"number","default":50,"step":0.01},
    "color": {"type":"string","default":"#f8c7ca"},
    "lineColor": {"type":"string","default":"#ffffff"},
    "lineWidth": {"type":"number","default":2,"step":0.01},
    "alpha": {"type":"number","default":1,"min":0,"max":1,"step":0.01},
    "speed": {"type":"number","default":30,"step":0.01}
  },
  "pinkStripes": {
    "stripeWidth": {"type":"number","default":150,"step":0.01},
    "speed": {"type":"number","default":0.5,"step":0.01},
    "angle": {"type":"number","default":-45,"step":0.01},
    "pinkColor": {"type":"string","default":"#fbbdbe"},
    "alpha": {"type":"number","default":1,"min":0,"max":1,"step":0.01}
  },
  "pixelBackground": {
    "pinkCount": {"type":"number","default":6,"min":0,"step":1},
    "yellowCount": {"type":"number","default":8,"min":0,"step":1},
    "checkerColor1": {"type":"string","default":"#ffffff"},
    "checkerColor2": {"type":"string","default":"#fef5f8"},
    "checkerCellSize": {"type":"number","default":40,"step":0.01},
    "checkerAlpha": {"type":"number","default":0.3,"min":0,"max":1,"step":0.01},
    "dotColor": {"type":"string","default":"#ffb3d9"},
    "dotSize": {"type":"number","default":4,"step":0.01},
    "dotSpacing": {"type":"number","default":12,"step":0.01},
    "dotAlpha": {"type":"number","default":0.15,"min":0,"max":1,"step":0.01},
    "pinkColor": {"type":"string","default":"#ffb3d9"},
    "yellowColor": {"type":"string","default":"#fff9b3"},
    "pinkAlpha": {"type":"number","default":0.5,"min":0,"max":1,"step":0.01},
    "yellowAlpha": {"type":"number","default":0.6,"min":0,"max":1,"step":0.01}
  },
  "pixelTypewriter": {
    "fontFamily": {"type":"string","default":"\"Courier New\", monospace"},
    "fillColor": {"type":"string","default":"$text"},
    "fontSize": {"type":"number","default":44,"step":0.01},
    "strokeColor": {"type":"string","default":"#ffffff"},
    "strokeWidth": {"type":"number","default":6,"step":0.01},
    "pixelSize": {"type":"number","default":1,"step":0.01},
    "letterSpacing": {"type":"number","default":3,"step":0.01},
    "shadowColor": {"type":"string","default":"$primary"},
    "shadowBlur": {"type":"number","default":0,"step":0.01},
    "shadowOffsetX": {"type":"number","default":3,"step":0.01},
    "shadowOffsetY": {"type":"number","default":3,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "charDelay": {"type":"number","default":0.08,"step":0.01},
    "cursorBlinkSpeed": {"type":"number","default":0.5,"step":0.01},
    "leftX": {"type":"number","default":0.25,"step":0.01},
    "rightX": {"type":"number","default":0.75,"step":0.01},
    "maxCharsPerSide": {"type":"number","default":10,"step":0.01},
    "showCursorWhenDone": {"type":"unknown"},
    "cursorColor": {"type":"string","default":"$primary"},
    "cursorWidth": {"type":"number","default":4,"step":0.01}
  },
  "pixelWindow": {
    "windowsData": {"type":"unknown"},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "width": {"type":"number","default":280,"step":0.01},
    "height": {"type":"number","default":200,"step":0.01},
    "borderWidth": {"type":"number","default":4,"step":0.01},
    "titleBarHeight": {"type":"number","default":28,"step":0.01},
    "bgColor": {"type":"string","default":"#ffffff"},
    "borderColor": {"type":"string","default":"$primary"},
    "titleBgColor": {"type":"string","default":"$primary"},
    "alpha": {"type":"number","default":0.95,"min":0,"max":1,"step":0.01},
    "anchorX": {"type":"number","default":0.5,"step":0.01},
    "anchorY": {"type":"number","default":0.5,"step":0.01},
    "icon": {"type":"unknown"},
    "fontFamily": {"type":"string","default":"\"Courier New\", monospace"},
    "titleColor": {"type":"string","default":"#ffffff"},
    "title": {"type":"string","default":"Window"},
    "content": {"type":"unknown"},
    "contentColor": {"type":"string","default":"$text"},
    "iconColor": {"type":"string","default":"$primary"},
    "iconSize": {"type":"number","default":60,"step":0.01},
    "colorOverrides": {"type":"object","default":{"#ffffff":"#ffffff","#ffb3d9":"#ffb3d9","#b3e5fc":"#b3e5fc","#c8f7dc":"#c8f7dc","#fff9b3":"#fff9b3"}}
  },
  "planet": {
    "color": {"type":"string","default":"#ffffff"},
    "infFontSize": {"type":"number","default":18,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "radius": {"type":"number","default":120,"step":0.01},
    "coreRadius": {"type":"number","default":12,"step":0.01},
    "tickLen": {"type":"number","default":5,"step":0.01},
    "lineExtend": {"type":"number","default":1.8,"step":0.01},
    "arcRadius": {"type":"unknown"},
    "arcAlpha": {"type":"number","default":0.08,"min":0,"max":1,"step":0.01},
    "colorOverrides": {"type":"object","default":{"#000000":"#000000"}}
  },
  "pulsingCircle": {
    "strokeColor": {"type":"string","default":"#ffffff"},
    "strokeAlpha": {"type":"number","default":0.8,"min":0,"max":1,"step":0.01},
    "strokeWidth": {"type":"number","default":8,"step":0.01},
    "radius": {"type":"number","default":250,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "outerStrokeColor": {"type":"string","default":"#ecbfc0"},
    "outerStrokeWidth": {"type":"number","default":3,"step":0.01},
    "outerStrokeAlpha": {"type":"number","default":0.6,"min":0,"max":1,"step":0.01},
    "animSpeed": {"type":"number","default":0.2,"step":0.01},
    "strokePulseAmount": {"type":"number","default":0.5,"step":0.01},
    "radiusPulseAmount": {"type":"number","default":0.08,"step":0.01},
    "enableBeatReact": {"type":"boolean","default":false}
  },
  "radialRectangles": {
    "count": {"type":"number","default":12,"min":0,"step":1},
    "baseColor": {"type":"string","default":"#1133aa"},
    "edgeColor": {"type":"string","default":"#cccc00"},
    "edgeBlur": {"type":"number","default":6,"step":0.01},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "rotSpeed": {"type":"number","default":0.08,"step":0.01},
    "growSpeed": {"type":"number","default":0.03,"min":0,"step":1}
  },
  "rulerGuide": {
    "color": {"type":"string","default":"#ffffff"},
    "alpha": {"type":"number","default":0.5,"min":0,"max":1,"step":0.01},
    "x": {"type":"number","default":0.12,"step":0.01},
    "y": {"type":"number","default":0.75,"step":0.01},
    "hLength": {"type":"number","default":0.85,"step":0.01},
    "vLength": {"type":"number","default":0.65,"step":0.01},
    "lineWidth": {"type":"number","default":1,"step":0.01},
    "tickSpacing": {"type":"number","default":12,"step":0.01},
    "majorEvery": {"type":"number","default":5,"step":0.01},
    "minorTickLen": {"type":"number","default":6,"step":0.01},
    "majorTickLen": {"type":"number","default":14,"step":0.01},
    "circleRadius": {"type":"number","default":8,"step":0.01}
  },
  "scalloppedBorder": {
    "color": {"type":"string","default":"#ffffff"},
    "alpha": {"type":"number","default":1,"min":0,"max":1,"step":0.01},
    "shadowColor": {"type":"string","default":"#f8c7ca"},
    "shadowAlpha": {"type":"number","default":0.6,"min":0,"max":1,"step":0.01},
    "shadowOffsetX": {"type":"number","default":0,"step":0.01},
    "shadowOffsetY": {"type":"number","default":8,"step":0.01},
    "circleRadius": {"type":"number","default":80,"step":0.01},
    "topY": {"type":"number","default":0,"step":0.01},
    "bottomY": {"type":"unknown"},
    "animSpeed": {"type":"number","default":0.2,"step":0.01},
    "moveAmount": {"type":"number","default":15,"step":0.01}
  },
  "scanlines": {
    "color": {"type":"string","default":"#003333"},
    "alpha": {"type":"number","default":0.15,"min":0,"max":1,"step":0.01},
    "spacing": {"type":"number","default":4,"step":0.01}
  },
  "scatteredShapes": {
    "count": {"type":"number","default":12,"min":0,"step":1},
    "color": {"type":"string","default":"$primary"},
    "alpha": {"type":"number","default":0.5,"min":0,"max":1,"step":0.01},
    "minSize": {"type":"number","default":10,"step":0.01},
    "maxSize": {"type":"number","default":40,"step":0.01},
    "shapes": {"type":"array","default":["square","diamond"]}
  },
  "scatteredText": {
    "chars": {"type":"unknown"},
    "count": {"type":"number","default":15,"min":0,"step":1},
    "color": {"type":"string","default":"$secondary"},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", \"Yu Mincho\", serif"},
    "minSize": {"type":"number","default":20,"step":0.01},
    "maxSize": {"type":"number","default":60,"step":0.01}
  },
  "screenBorder": {
    "color": {"type":"string","default":"$primary"},
    "lineWidth": {"type":"number","default":1.5,"step":0.01},
    "alpha": {"type":"number","default":0.6,"min":0,"max":1,"step":0.01},
    "margin": {"type":"number","default":20,"step":0.01},
    "gap": {"type":"number","default":6,"step":0.01},
    "starSize": {"type":"number","default":5,"step":0.01},
    "edgeStarCount": {"type":"number","default":5,"min":0,"step":1},
    "edgeStarCountV": {"type":"number","default":3,"min":0,"step":1}
  },
  "shadowShapes": {
    "color": {"type":"string","default":"#ffffff"},
    "shadowColor": {"type":"string","default":"#000066"},
    "shadowAlpha": {"type":"number","default":0.5,"min":0,"max":1,"step":0.01},
    "shadowOffX": {"type":"number","default":12,"step":0.01},
    "shadowOffY": {"type":"number","default":14,"step":0.01},
    "count": {"type":"number","default":4,"min":0,"step":1},
    "shapes": {"type":"unknown"}
  },
  "shatterText": {
    "fontSize": {"type":"number","default":120,"step":0.01},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", \"Yu Mincho\", serif"},
    "fontWeight": {"type":"string","default":"900"},
    "color": {"type":"string","default":"$text"},
    "alphaThreshold": {"type":"number","default":128,"min":0,"max":255,"step":1},
    "minAreaFrac": {"type":"number","default":0.001,"step":0.01},
    "preErosionIters": {"type":"number","default":0,"step":0.01,"min":0},
    "charSpacingFrac": {"type":"number","default":1.05,"step":0.01},
    "scatterRadiusFrac": {"type":"number","default":0.3,"step":0.01},
    "scatterScaleMin": {"type":"number","default":0.4,"step":0.01},
    "staggerDelay": {"type":"number","default":0.05,"step":0.01},
    "randomDelayRange": {"type":"number","default":0.35,"step":0.01},
    "durationVariation": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01},
    "fitMarginX": {"type":"number","default":0.86,"step":0.01},
    "fitMarginY": {"type":"number","default":0.75,"step":0.01},
    "minFontSize": {"type":"number","default":24,"step":0.01},
    "mode": {"type":"string","default":"gather","options":["gather","oscillate","beatPulse"]},
    "gatherDuration": {"type":"number","default":0.8,"step":0.01,"min":0.05},
    "oscillateFreq": {"type":"number","default":0.3,"step":0.01},
    "oscillateAmount": {"type":"number","default":0.08,"step":0.01},
    "beatDispersion": {"type":"number","default":0.6,"step":0.01}
  },
  "smearBrush": {
    "grainAlpha": {"type":"number","default":0.04,"min":0,"max":1,"step":0.01},
    "count": {"type":"number","default":8,"min":0,"step":1},
    "colors": {"type":"unknown"}
  },
  "staggeredText": {
    "fontSize": {"type":"number","default":64,"step":0.01},
    "colChars": {"type":"number","default":5,"step":0.01},
    "frameColor": {"type":"string","default":"#ffffff"},
    "frameAlpha": {"type":"number","default":0.6,"min":0,"max":1,"step":0.01},
    "framePadding": {"type":"number","default":30,"step":0.01},
    "text": {"type":"unknown"},
    "modeDuration": {"type":"number","default":3,"step":0.01},
    "color": {"type":"string","default":"#ffffff"},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", \"Yu Mincho\", serif"},
    "transition": {"type":"number","default":0.4,"step":0.01}
  },
  "starTrail": {
    "count": {"type":"number","default":20,"min":0,"step":1},
    "strokeWidth": {"type":"number","default":3,"step":0.01},
    "radiusX": {"type":"number","default":600,"step":0.01},
    "radiusY": {"type":"number","default":400,"step":0.01},
    "maxSize": {"type":"number","default":260,"step":0.01},
    "minSize": {"type":"number","default":35,"step":0.01},
    "loopSpeed": {"type":"number","default":0.12,"step":0.01},
    "tilt": {"type":"number","default":-0.25,"step":0.01},
    "arcCenter": {"type":"number","default":-0.6,"step":0.01},
    "arcSpan": {"type":"number","default":4.2,"step":0.01},
    "curveFrac": {"type":"number","default":0.45,"step":0.01}
  },
  "targetGuide": {
    "color": {"type":"string","default":"#6666cc"},
    "alpha": {"type":"number","default":0.4,"min":0,"max":1,"step":0.01},
    "rings": {"type":"array","default":[0.12,0.18,0.26]},
    "tickCount": {"type":"number","default":8,"min":0,"step":1}
  },
  "textCards": {
    "text": {"type":"unknown"},
    "cardColor": {"type":"string","default":"$primary"},
    "textColor": {"type":"string","default":"$background"},
    "fontSize": {"type":"number","default":80,"step":0.01},
    "padding": {"type":"number","default":30,"step":0.01},
    "spawnInterval": {"type":"number","default":0.4,"min":0,"step":1},
    "lifetime": {"type":"number","default":2.5,"step":0.01},
    "borderColor": {"type":"string","default":"$accent"},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", \"Yu Mincho\", serif"}
  },
  "textStrip": {
    "stripColor": {"type":"string","default":"$secondary"},
    "stripWidth": {"type":"number","default":80,"step":0.01},
    "stripHeight": {"type":"number","default":600,"step":0.01},
    "rotation": {"type":"number","default":-30,"step":0.01},
    "stripAlpha": {"type":"number","default":0.85,"min":0,"max":1,"step":0.01},
    "text": {"type":"unknown"},
    "textColor": {"type":"string","default":"$text"},
    "fontSize": {"type":"number","default":60,"step":0.01},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", \"Yu Mincho\", serif"},
    "x": {"type":"number","default":0.5,"step":0.01},
    "y": {"type":"number","default":0.5,"step":0.01}
  },
  "textureBackground": {
    "intensity": {"type":"number","default":0.15,"step":0.01},
    "driftSpeed": {"type":"number","default":0.5,"step":0.01}
  },
  "triangleGrid": {
    "color": {"type":"string","default":"$secondary"},
    "alpha": {"type":"number","default":0.2,"min":0,"max":1,"step":0.01},
    "cols": {"type":"number","default":10,"min":0,"step":1},
    "filled": {"type":"boolean","default":false},
    "fillColor": {"type":"string","default":"#002200"},
    "fillAlpha": {"type":"number","default":0.08,"min":0,"max":1,"step":0.01}
  },
  "verticalSubText": {
    "color": {"type":"string","default":"#ffffff"},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", \"Yu Mincho\", serif"},
    "fontSize": {"type":"number","default":14,"step":0.01},
    "x": {"type":"number","default":0.62,"step":0.01},
    "y": {"type":"number","default":0.35,"step":0.01},
    "charsPerCol": {"type":"number","default":5,"step":0.01}
  },
  "victimOutline": {
    "color": {"type":"string","default":"#ffffff"},
    "alpha": {"type":"number","default":0.88,"min":0,"max":1,"step":0.01},
    "scale": {"type":"number","default":1.5,"step":0.01},
    "lineWidth": {"type":"number","default":5,"step":0.01},
    "seed": {"type":"number","default":0,"min":0,"step":1},
    "x": {"type":"unknown"},
    "y": {"type":"unknown"},
    "rotation": {"type":"unknown"}
  },
  "vignette": {
    "intensity": {"type":"number","default":0.6,"step":0.01}
  },
  "waveText": {
    "staggerY": {"type":"number","default":18,"step":0.01},
    "blendMode": {"type":"string","default":"difference"},
    "charSpreadFrac": {"type":"number","default":0.5,"step":0.01},
    "fontSize": {"type":"number","default":52,"step":0.01},
    "color": {"type":"string","default":"#ffffff"},
    "fontFamily": {"type":"string","default":"\"Noto Serif JP\", serif"},
    "fontWeight": {"type":"string","default":"900"}
  },
  "webLines": {
    "count": {"type":"number","default":22,"min":0,"step":1},
    "focalX": {"type":"number","default":0.5,"step":0.01},
    "focalY": {"type":"number","default":0.45,"step":0.01},
    "spread": {"type":"number","default":0.25,"step":0.01},
    "color": {"type":"string","default":"#ff2222"},
    "glowColor": {"type":"string","default":"#ff4444"},
    "rebuildChance": {"type":"number","default":0.008,"step":0.01}
  }
};
